/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Takoyaki(props) {
  const { nodes, materials } = useGLTF("/takoyaki.glb");
  const groupRef = useRef();

  useFrame((state) => {
    const time = state.clock.elapsedTime;

    // Float up and down
    groupRef.current.position.y = Math.cos(time) * 0.15;

    // Rotate to face corners
    groupRef.current.rotation.x = Math.sin(time * 0.5) * 0.25; // up / down
    groupRef.current.rotation.y = Math.cos(time * 0.5) * 0.25; // left / right
  });

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials.takoyaki}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Top.geometry}
        material={materials.Sauce}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BézierCurve.geometry}
        material={materials.Cream}
      />
    </group>
  );
}

useGLTF.preload("/takoyaki.glb");
